name: Run test-coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Start the app for Cypress tests
        run: npm run e2e:ci
        env:
          CI: true

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:4200 # Adjust URL if needed

      - name: Run Cypress E2E tests
        run: npm run cy:run

      - name: Merge coverage reports
        run: npm run coverage:all

      - name: Upload merged coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/merged/lcov.info
          verbose: true
